### ISSUE TITLE
`duu` v2.30 standalone Windows executable triggers Windows Defender

### ISSUE THREAD

**Issue by hrxn** [jftuga/duu#1]
Oh, hey. Looks like I have the honor to open the very first issue here 😄 

The issue title pretty much describes the entire issue, already. Windows Defendrer complains, with *Threat Level: Severe*, and proceeds to delete `duu.exe` immediately.

I assume it's made with PyInstaller? Not sure, but I think this is pretty notorious already for false positives etc.
Guess someone should inform Microsoft?

I have used `duu.py` in the past, actually, but with the new release I wanted to try the standalone binary.

**Comment by jftuga** [comment]
It was created with `PyInstaller`.  

The [duu virus total](https://www.virustotal.com/gui/file/b4381b16e4779cca23485c9c64ecf3222fca47fca601fe86fb11a8705d78abe3) results aren't looking great.

I'll look into this.  Thanks for the report.

**Comment by jftuga** [comment]
@Hrxn 

I created a new binary using [Nuitka](https://nuitka.net/).  VirusTotal [reports](https://www.virustotal.com/gui/file/1b3ec59c4c824d29fd6542d876ff3bb2c68ee5dbc13a4d708d68c1690340e2f6?nocache=1) false positives, but not for Microsoft.  Can you please try this version which is in the [releases](https://github.com/jftuga/duu/releases/tag/v2.30) section?

**Comment by hrxn** [comment]
Guess what happened..

![snip1](https://github.com/jftuga/duu/assets/12064918/be4b0a17-3e18-422d-8f03-317d3899ac6b)

![snip2](https://github.com/jftuga/duu/assets/12064918/fa4dec4e-8da1-42c4-9e6b-7126f479ac2a)


Same as before, Windows Defender removes the file after a few seconds, even without me doing any kind of confirmation click..

But then I tried the other binary again:

```
PS C:\Apps\Temp> curl 'https://github.com/jftuga/duu/releases/download/v2.30/duu.exe'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 7940k  100 7940k    0     0  6138k      0  0:00:01  0:00:01 --:--:-- 27.0M
[curl] : HTTP/2 200 'GET' [application/octet-stream] (https) | Exitcode: 0 | Duration: 1.293431s | Output: 'duu.exe' | Domain: 'https://objects.githubusercontent.com'
PS C:\Apps\Temp> ls

    Directory: C:\Apps\Temp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2023-12-21    17:38                20231221
d----          2023-12-20    03:15                Mozbackup
-a---          2023-12-23    18:53        8130639 duu.exe
-a---          2023-12-17    17:17          34479 if-t.txt
-a---          2023-11-18    19:38         390586 if.txt
-a---          2023-12-23    18:49         221881 snip1.png
-a---          2023-12-23    18:51         151855 snip2.png

PS C:\Apps\Temp>
```

And this time Windows Defender did *not* intervene. `duu.exe` is still there, and I can run it..

Guess it took some time to build up "Immunological memory" 😆 

I also did a check with VT again and hit this *reanalyze* button. It does not get flagged by Microsoft there any longer, so this seems to fit.

*Edit*

~~Rephrasing, because misleading:~~
~~The *Nuitka* binary was not flagged on VT by Microsoft, as your scan link shows, but it still triggered Windows Defender locally.~~

This other link is from the older *PyInstaller* binary, which shows up as "clean" by Microsoft on VT, as before.

https://www.virustotal.com/gui/file/b4381b16e4779cca23485c9c64ecf3222fca47fca601fe86fb11a8705d78abe3

*Edit 2*

Waaait...
Confused the scan results. *Nuitka* binary was actually flagged by Microsoft as "Trojan:Win32/Wacatac.B!ml" on VT, when you posted your second comment. The *PyInstaller* does not anymore meanwhile.

---


This will probably also happen with the *Nuitka* binary after some time, I assume.

But I'm a bit curious, there is a difference of about 2.6 MiB between those two binaries, do you know what would explain this by chance?

**Comment by jftuga** [comment]
Thanks for thoroughly investigating this.  When I build with `PyInstaller` I do not use `upx` compression because it seems to make the binary not work.  OTOH, the  `Nuitka` binary looks like it is already internally compressed (but not with `upx`).  This is my best guess as to the different file sizes.

**Comment by hrxn** [comment]
Ah, I see, this would indeed explain the size difference. And be consistent with the usual rule of thumb of "more binary compression -> more positive detections on VirusTotal", which is what we have seen here so far.

Anyway, for all intents and purposes, I don't think there is anything that can be realistically done here on the side of this project.

This isn't even a new issue, this has been going on for quite some time now.

https://github.com/pyinstaller/pyinstaller/issues?q=wacatac

I guess there's not much to expect here given the combination of actual malware authors commonly using Python and PyInstaller and overzealous "AI" infused anti-virus  software, so I'm closing this issue here with this comment.

Of course, feel free to reopen etc. if you feel like it.

**Comment by jftuga** [comment]
No need to reopen as you are correct - nothing more to be done at this point.  Thanks for spending the time  researching this.

I'm really glad you like using the program. 😃

FWIW, using `-T 4` (four concurrent threads) seems to give me the best throughput.

**Comment by sergeevabc** [comment]
I am sorry, is there a way to get bytes only under Windows without tricks?

``` console
$ duu -q C:\Test

summary
=======
files         : 60 531
directories   : 7 136
bytes         : 3 012 235 061
kilobytes     : 2 941 635,80
megabytes     : 2 872,69
gigabytes     : 2,81

$ duu -q C:\Test | rg "^bytes.*:\s(.*)" -r $1
3�012�235�061

```
